### ISSUE TITLE
Chess Engine

### ISSUE THREAD

**Issue by stockfishdeveloper** [DmitryAleksandrovich/FileSystemParser#1]
Hi there!

I'm stockfishdeveloper and you contacted me about assisting me with the engine. Are you still interested?

stockfishdeveloper(David)

**Comment by DmitryAleksandrovich** [comment]
Hi!
Yes, but I'm a little hard to understand in the project generally. I
understand all code. But, to create a good patch, that's more difficult.
Maybe, you tell me what to do or tell me priorities (classes).
I really want to participate in your projects. The lack of experience
affects teamwork :(
I hope for your understanding.

**Comment by stockfishdeveloper** [comment]
Alright. I will try to explain most of the chess engine. I am busy right now, but I will try to get it to you by tonight. Also, don't feel bad about not being an expert at C++. I was once where you were!

**Comment by stockfishdeveloper** [comment]
Alright, here goes. Hopefully you know how to play chess.

First of all, the most important thing right now is optimization. If you see any parts that can be optimized, that would be great. 

Here is how the engine works:
Take a look in main.cpp;  it has a method called initmagicmoves() to initialize the bitboards found in magicmoves.c
It also has a CheckUci method. The CheckUci method(in UCI.cpp) basically takes in the GUI(Chessbase, Arena) commands and processes them. It then does what the command says and perhaps send some information back to the GUI. Also, all input that the program gets is put in the Log stream. Do you know the uci protocol? If not, let me know and I can get you a copy. The most important command the engine gets is the “go” command. When it gets this command, the engine first takes in the commands the GUI sends(“wtime”, “btime”) and just puts them in a string; we won’t need them again. After that, a thread is started by the following command: thread t(Runthread, &PVline); This thread allows the program to take in input(the main thread) and to put out information to the GUI(with the t thread). After that, a few lines down, is: blank = Think(wtime, btime, h, j); this is the main searching method. Think() is the method and its parameters are the amount of time white has, the amount of time black has, and the time increment(if any). After the best move is returned from Think(), the engine executes the move on the internal bitboards with the MakeMove() method. 

There are not many classes in this project, mainly because a chess engine is all about speed and I have heard that object-oriented programming is inefficient for chess engines. 

Again, the best thing you can do for the project right now is to find little optimizations that overall will boost the performance. 

Thank you!

**Comment by DmitryAleksandrovich** [comment]
Hi!
Thanks, for the clarifications. I do't know the uci protocol (unfortunately
).
Now, I'll understand with your letter and with chess engine.

Thanks, for your responses!
If I'll have some questions than I'll write to you.
If you will have some recomendation, than will write to me. Often, I just
can't read letters because of the time difference. But I'll read their
allways later.

**Comment by stockfishdeveloper** [comment]
[Uci Protocol.txt](https://github.com/DmitryAleksandrovich/software-projects/files/44263/Uci.Protocol.txt)
Here is the uci protocol. It is the attached text file. It tells all the commands the chess engine receives and sends. Also, you should probably get a GUI like chessbase or Arena(playwitharena.com). Please look for any optimizations in the engine.

David

**Comment by DmitryAleksandrovich** [comment]
I'a reading the book about Chess Engine: algoritm MiniMax, NegaMax,
Alpha-Beta, MVV/LVA... I looked at the code and found a places (code) that
can be improved, for example: int MakeMove(Move& Best_Move) -> int
MakeMove(Move _const_& Best_Move) and for( int h = 0; h < 64; h++) -> for(
int h = 0; h < 64; _++_h) = (not will be copy value "h")...
I'm learning algorithms now and code to better understand. I want to
understand how to make changes to the test and not just in the code.

**Comment by stockfishdeveloper** [comment]
Good job! Passing the move by const reference is better than by reference. Also, why do ++h instead of h++? This is in your second suggestion. Yes, you should learn NegaMax and alpha beta. I found them hard, but if you have any questions, just ask me!

Thank you
David

**Comment by stockfishdeveloper** [comment]
You might want to have a look at https://chessprogramming.wikispaces.com
It has very good explanations of search methods.

**Comment by DmitryAleksandrovich** [comment]
When we write "h++" then the compiler create a temporary object, make
increment and return the original value. Post-increment that's create a
temporary object.
Thank you for the link! I think it useful. It's hard information, but I
think I'll deal:)

If you're comfortable, my skype: dima_popov22

**Comment by stockfishdeveloper** [comment]
Post increment creates a temporary object? How is that more efficient than pre increment?
Unfortunately, I am not on Skype often. I'll try to go on though.

**Comment by stockfishdeveloper** [comment]
Make a pull request with all your changes that you find. I will probably commit them.

**Comment by DmitryAleksandrovich** [comment]
Pre increment do't create a temporary object and it does't require much
resources how post increment. Though, for type *int *it's a slight
advantage and for user-defined types it's greatly.

We have late night and I am forced to go to sleep. But at morning I will
return to engine)

**Comment by stockfishdeveloper** [comment]
Good get some rest.

**Comment by DmitryAleksandrovich** [comment]
Hi, David!
I understood Alpha Beta Pruning (MiniMax)☺ I decided to tasks and now, I
can to work with code:)
Are my tasks old?

**Comment by stockfishdeveloper** [comment]
Okay, I have a job for you. Take a look at abrok.eu/stockfish and download the latest version of the stockfish engine. Type in the command: go wtime 345678 btime 345678. Look at how the engine outputs the information to the GUI. See if you can understand what it is knowing. Let me know if you don't understand. Also, the most important thing for you to do right now is to be able to compile the engine. Do this before anything else. Use Dev-Cpp for the compiling. Let me know if you are having trouble compiling it. 

David

**Comment by stockfishdeveloper** [comment]
Also, if you have any suggestions of code, make a pull request. 

Thank you!

Dave

**Comment by DmitryAleksandrovich** [comment]
Hello, Dave! I downloaded the last version of the stockfish engine, entered
the command "go wtime 345678 btime 345678". In the attached file results. I
do't understend what to do next. Does that application imitates Chess and
find the best move? Would you like to make somethink similar?

**Comment by stockfishdeveloper** [comment]
Stockfish will output the string "bestmove " and then a move. This is the result of Stockfish searching the start position of chess. Enter the same command in my engine after you compile it and it will output a bestmove command saying the best move for the position. Check the uci.txt file i gave you in an above post. PLEASE LET ME KNOW IT YOU CAN COMPILE MY PROJECT.

Thank you,

Dave

**Comment by DmitryAleksandrovich** [comment]
I can not compile your project, I have a syntax errors. My IDE produces
errors and warnings. Photo in the attached file. I'd like to work on them.

Thank you!

**Comment by stockfishdeveloper** [comment]
Yes, compiling it is hard. If you cannot, I can give you a compiled copy of the engine. Also, so I can help you compile my engine, I need to know what errors there are; can you give me some snippets of the compiler output? I did not find the attached picture. Please let me know what errors the compiler is giving you and I can help you compiling it.
Thank you,

Dave

**Comment by DmitryAleksandrovich** [comment]
Hi, Dave! If you can give me a complited copy of the engine, please. I wrote the last later with email and the attached file not found. I attach the picture again but through GitHub.
![compile](https://cloud.githubusercontent.com/assets/15381269/11457835/f5d5ca1c-96bb-11e5-8189-db19f1b95c5d.jpg)
Thanks.

**Comment by stockfishdeveloper** [comment]
Thank you, Dmitry. I just got the picture and I'll give you a copy of the compiled engine. How  is a 32-bit compile? I'll help you with compiling the engine after I look at at the picture.

Thank you,

Dave

**Comment by stockfishdeveloper** [comment]
Also, Use Dev-Cpp(http://sourceforge.net/projects/orwelldevcpp/files/Setup%20Releases/Dev-Cpp%205.11%20TDM-GCC%204.9.2%20Setup.exe/download) Install it and try to compile with that. That is what I use to compile.

**Comment by stockfishdeveloper** [comment]
Ask me if you don't know how to use Dev-Cpp.

**Comment by DmitryAleksandrovich** [comment]
I installed Dev-Cpp and tried to compile with that. But errors more than in Visual Studio. I red their and I did't undertand, the absurdity of some. Maybe it's my OS. Photo in the attached file:)
Thank Dave, for helping me!
![dev-cpp](https://cloud.githubusercontent.com/assets/15381269/11458205/588b7bd6-96c4-11e5-8e28-cb781cfef696.jpg)

**Comment by stockfishdeveloper** [comment]
I got that error too in Dev-Cpp. I will work on it and let you know as soon as I can so you can start working on the engine.

Dave

**Comment by stockfishdeveloper** [comment]
Okay, open the attached "chrono.txt" file and save it as a header file(.h). Put that in the folder C:\Program Files\Dev-Cpp\MinGW64\x86_64-w64-mingw32\include and then try to compile. Please let me know if it does not work. Don't worry, we'll get you compiling this engine soon.
[chrono.txt](https://github.com/DmitryAleksandrovich/software-projects/files/46724/chrono.txt)

**Comment by stockfishdeveloper** [comment]
Also, I saw in the picture that you had the header files open. Close them and click Rebuild all in the Execute menu. You can close the header files by right-clicking on them and clicking close.

**Comment by stockfishdeveloper** [comment]
Okay, also, right click on the .h files in the column on the left in Dev-cpp, the column that says "Project" and click "remove file". This will probably remove some of the warnings. Also, right click in the "project" column and add the other .cpp files in the repository download folder of my engine.

**Comment by DmitryAleksandrovich** [comment]
I did everything that you said, but warnings and errors stayed. Photo in the attached file:

![dev-cpp](https://cloud.githubusercontent.com/assets/15381269/11459649/17f6e676-96e4-11e5-9d22-684bb3a18ec1.jpg)

**Comment by stockfishdeveloper** [comment]
Okay, I think i have the solution: go to tools/compiler options/general/and check the box labeled "Add the following commands to the compiler" After you check the box, type in the field below the box: -std=gnu++11 That might work. I am on for a while, we can talk quickly now.

Dave

**Comment by DmitryAleksandrovich** [comment]
Nothing:(
I think, maybe, I can to make small changes and compiled all project later.
How do you think, Dave?
Just I'd like to participate in the project, understand microenvironment of
the project.

Thank you!

**Comment by stockfishdeveloper** [comment]
Sure, any changes would be helpful, I just thought that you would want to be able to compile the project. Go ahead and make a pull request or tell me of your changes. By the way, I already committed your earlier suggestions. Again, good job!

Dave

**Comment by DmitryAleksandrovich** [comment]
I think I can to compile the project when I undestand it.
Sorry, that I distract you on Sunday.
Good luck!

**Comment by stockfishdeveloper** [comment]
No, that's okay, forget compiling it for now and just make some changes. Four eyes are better than two!

Dave

**Comment by stockfishdeveloper** [comment]
Hi Dmitry,
Could you focus on MoveGen.cpp and look for some changes?
Thank you,
Dave

**Comment by DmitryAleksandrovich** [comment]
Of couse, I'll lock MoveGen.cpp. Sorry, that I disappeared for a few days.
A lot of work collected.
Thank you.

On Wed, Dec 2, 2015 at 8:44 PM, stockfishdeveloper <notifications@github.com

**Comment by stockfishdeveloper** [comment]
I was very sick the last two days and I could not work on the project either.
Dave

**Comment by DmitryAleksandrovich** [comment]
Good health, Dave!
I'll try to work to the project today. And I'll try not to bother you:)

On Wed, Dec 2, 2015 at 9:46 PM, stockfishdeveloper <notifications@github.com

**Comment by stockfishdeveloper** [comment]
All right, I think I'm over the sickness and I'll try to make some commits to the engine soon.
Good luck,
Dave

**Comment by DmitryAleksandrovich** [comment]
It's good. I can to make for the project not very much and I think I try to
write a few tests on Boost (for example).
How do you think?
Thank you.

**Comment by stockfishdeveloper** [comment]
Hi Dmitry,
I had a little trouble understanding your last message; perhaps you could use google translate and post the translation here?
Thank you,
Dave

**Comment by DmitryAleksandrovich** [comment]
I'm sorry!
Google translate it's bad idea:) It translates poorly.
I want to ask: can I to write unit test through the library Boost?
Sorry with my not very confident English.

**Comment by stockfishdeveloper** [comment]
Sure, but it might be hard. What kind of unit test did you have in mind?
Dave

**Comment by DmitryAleksandrovich** [comment]
I do't know yet.
But I'd like to bring real help to the project.
And now I still do't make commits. But I understand the file MoveGen.cpp.

Thank you.

**Comment by stockfishdeveloper** [comment]
Hey Dmitry,
Github just introduced a new interface, and I cannot commit to a file by editing it. I go into the file and click the little pencil icon and then make my changes but then the green commit button at the bottom does not light up and let me commit. Do you why this is happening? also, I am using Windows XP so I cannot use Github for Windows. Do you know of any other way I can commit to my repository?

Thanks for your help,
Dave

**Comment by stockfishdeveloper** [comment]
Whoops..
Sorry, now it is working; last night it was not working, maybe they fixed it after they put in the new interface.
Dave

**Comment by DmitryAleksandrovich** [comment]
Yes, now it's working.
Maybe, only last night, because a few days ago I brought the test changes.
But I'm using Windows 7.

On Fri, Dec 4, 2015 at 7:09 PM, stockfishdeveloper <notifications@github.com

**Comment by DmitryAleksandrovich** [comment]
Hi Dave!
I made a little optimization in Eval.cpp.
If you got change, please let me know about it.

Thank you.

**Comment by stockfishdeveloper** [comment]
Very good try, Dmitry, but I need to know how many of each piece are on the board, not if there are any. For example, if there were two white knights on the board, the bool would pick up that there was a t least on white knight and there would be only one knight scored in the evaluation. See what I mean?
Thanks and keep the pull request coming,
Dave

**Comment by stockfishdeveloper** [comment]
Wait a minute... I didn't see that you left the top for loop in the file... actually your suggestion might work. I'll try it on my machine and if it is faster then I'll merge it.
Thank you!
Dave

**Comment by stockfishdeveloper** [comment]
Congratulations! You've got a winner! This is a great speedup(20%) on my machine!
Great job! I'll commit your pull request right away.
Thanks again and keep the pull requests coming,
Dave

**Comment by DmitryAleksandrovich** [comment]
Thank you Dave!
I will try benefit project. Great day for me:)
I'm learning English and so I write a shot email. But before long I hope I
will write a longer letters.

On Sat, Dec 5, 2015 at 5:39 PM, stockfishdeveloper <notifications@github.com

**Comment by stockfishdeveloper** [comment]
Hi Dmitry,
I noticed in Eval.cpp that you did not optimize the part that adds the values from the piece square tables. I see your trick will work in that part of the function too. I will commit this as soon as I can.
Dave

**Comment by DmitryAleksandrovich** [comment]
Hi.
Sorry, I did't see it.
I'll try to be careful in the future.
Thank you.

On Sun, Dec 6, 2015 at 8:09 PM, stockfishdeveloper <notifications@github.com

**Comment by stockfishdeveloper** [comment]
You definitely get the credit for spotting the original idea.
Keep up the good work,
Dave

**Comment by stockfishdeveloper** [comment]
Alright, Dmitry, I've got a project for you. This is a chance to really help me with the project. I just made a release in the C++ Bitboard Chess Engine repository. Download it and play around with it for a little while. The job for you is to figure out why the engine is outputting wrong information. Basically, you type in:
startpos
go wtime 34567 btime 34567
and the engine will output some info and then follow that with:
bestmove X
where X is its move.
startpos command means that the engine should set up the original position on the internal bitboards(See UCI.cpp)
The go command means that the engine should start thinking and then return its bestmove command. The numbers after the go command mean how much time in milliseconds the engine has left in the game to think. wtime means "white's time" and btime means "black's time"
If you did not understand anything of what I just said, look at the uci.txt file I gave you; it explains it all. 

Ok, here it the assignment for you: when you type in the list of commands that I showed you(startpos, go wtime 34567 btime 34567) the engine works fine, but when you type in those same commands again, the engine freezes and does not send the "bestmove" command. If you type in the commands again, then it seems to work. Every other time the engine seems to not send it bestmove command. I want you to try to figure out why this is happening using the engine and the source code. I am working on it right now but haven't been able to figure it out. 

Thanks Dmitry,
Dave

**Comment by stockfishdeveloper** [comment]
Also Dmitry, do you know how to use the ZThreads threading library? I am currently using the Tinythreads threading library but it seems not good enough for my needs. I will be making a huge commit making the engine use threads in its search, hopefully doubling its speed in positions per second. I am using Tinythreads now for output to the GUI while the engine is searching.
Thanks,
Dave

**Comment by DmitryAleksandrovich** [comment]
Hi.
No, I don't know ZThreads threading library. But tomorrow I will understand
with it.
Now, I'm trying to compile the project. Because I can't normal to work and
to perform your request two days ago (I remember about it).

Thank you.

**Comment by stockfishdeveloper** [comment]
Ok Dmitry, I just figured out how you can compile the project!
I assume you are using Dev-cpp like I told you, so go to Project > Project Options and go to the tab compiler options or something similar. Put the "Language" tab onto gnu++11 or the one close to that. This should get rid of most of the errors. If you still can't compile, show me a picture of the errors after you do what I told you in this post.

Thank you,
Dave

**Comment by stockfishdeveloper** [comment]
Hi Dmitry,
Are you able to compile the project yet?
Dave

**Comment by DmitryAleksandrovich** [comment]
Hi Dave.
I can't still to compile the project. I made as you said but there is one error. Photo in the attached file.
I hope than you've seen that error once.
Thank you.
![compile](https://cloud.githubusercontent.com/assets/15381269/11701645/5f7a5e86-9ed9-11e5-930e-ffbfa8233589.jpg)

**Comment by DmitryAleksandrovich** [comment]
Hi Dave.
I can't still to compile the project. I made as you said but there is one error. Photo in the attached file.
I hope than you've seen that error once.
Thank you.
![compile](https://cloud.githubusercontent.com/assets/15381269/11702233/c76e5606-9edd-11e5-9fcd-ab2ba8d45624.jpg)

**Comment by stockfishdeveloper** [comment]
Hi Dmitry, I have seen the error before and this is how to fix it: go to the column on the left that shows all the .cpp and .h files and right-click on all the .h files. Select "Remove file" on all of them. After that, right-click on the "magicmoves.cpp" file and select "Remove file". Then rebuild all and most of the errors should be gone. There will still be the errors with "undefined reference to ttthread(), but we will fix those as soon as you reply to this.
Thanks,
Dave

**Comment by DmitryAleksandrovich** [comment]
Hi.
I used this and I have error: "undefined reference to
`tthread::thread::thread(void (_)(void_), void*)'".
I think I will compile the project tonight:)
Thank you,
Dima

**Comment by stockfishdeveloper** [comment]
[tinythread.txt](https://github.com/DmitryAleksandrovich/software-projects/files/58629/tinythread.txt)

Ok, here is how to fix the errors in the project: download the text file I attached in notepad and save it as a .cpp file. Make sure you name it "tinythread" and that you save it as type "all files". Then put the tinythread.cpp into the folder where you keep the source for the engine. Then, in Dev-cpp, go to 
Project > Add to project and add the tinythread.cpp file to the project. Then rebuild all and it may actually compile. We are almost there! 
By the way, would it be possible for me to access your computer virtually so that I can get Dev-cpp to compile for you? I don't know much about wireless access.  

Thank you,
Dave

**Comment by DmitryAleksandrovich** [comment]
Well, I builded the project but debug doesn't work.
Error:
(gdb)
->->prompt

->->post-prompt
Working directory
C:\Users\Dima\Documents\Dev_Cpp\projects\C---Bitboard-Chess-Engine-master.

->->pre-prompt
(gdb)
->->prompt

->->post-prompt
Starting program:

->->error

->->pre-prompt
(gdb)
->->prompt

->->error-begin
_No executable specified, use `target exec'._

Thank you.

**Comment by stockfishdeveloper** [comment]
Ok, in Dev-cpp go to Project > Project Options and look at the label "Output file" it will display the path to the .exe that Dev-cpp made. The build was successful, wasn't it? You can run the program after you build it by going to Execute > Run. It will run the engine that you compiled. Please let me know if you have built it successfully. I am going to sleep now and I will respond about 10 hours from the time of this note.
Thanks Dmitry,
Dave

**Comment by DmitryAleksandrovich** [comment]
Hi.
Yes, I builded it but then I run the program and I have error: "Failed to
execure .exe...".
The path to the .exe is correct. I thought this problem is related to the
location of the project (russian symbols in the path) but it is not.
Thank you.

**Comment by stockfishdeveloper** [comment]
What operating system are you on? w32 or w64? If you are on w32, make sure that in the upper right hand corner of Dev-cpp the drop down menu says "TDM-GCC (any number) 32-bit  Release. If it does not, change the choice to the one I just said. This is if you are on a 32-bit operating system. It happens to me sometimes because you are trying to build and run a 64-bit program on a 32-bit computer.
Thanks,
Dave

**Comment by DmitryAleksandrovich** [comment]
Thanks Dave very much!
I builded and runed the project. I changed the choice: Project->Project
options->Compiler->Code generation->Compile with the following pointer
width (32 bit).

Thank you.

**Comment by stockfishdeveloper** [comment]
Alright,  good job!. I have a task for you: can you run the engine you compiled and type in the following commands: 
startpos
go wtime 345678 btime 345678

The engine will put out a lot of text about its search. Your task is to look for each of the "nps" part in the output. After each "nps" you will see a number. Please tell me what some of the numbers are. This will tell me how fast you computer is compared to mine.
Thanks Dmitry!
Dave

**Comment by DmitryAleksandrovich** [comment]
Well. The program doesn't work propertly.
Photo in the attached file.
![result](https://cloud.githubusercontent.com/assets/15381269/11753737/9dcb5650-a04f-11e5-8edd-1697b1412b62.jpg)

**Comment by DmitryAleksandrovich** [comment]
But .exe of the last release gives the following result:
![result2](https://cloud.githubusercontent.com/assets/15381269/11753815/1cceab82-a050-11e5-8aa9-fae6a16e6279.jpg)

**Comment by stockfishdeveloper** [comment]
Ok, first of all, your computer is much faster than mine. The reason the engine you compiled is not working is probably because you have enabled certain instructions in the .exe. To fix this, in Dev-cpp go to Project > Project Options and go to the compiler tab. Go to the Code Generation tab. On the drop down menus on the right, there will be one column called "Enable the use of specific instructions(-mx)". Put the menu selection to  the blank choice and then rebuild the project. This should fix your problem. If it doesn't, then let me know. 
Thanks,
Dave

**Comment by DmitryAleksandrovich** [comment]
This column (Enable the use of specific instructions(-mx)) is blank.
The work of Dev-Cpp after the run:
Thank you.
![result](https://cloud.githubusercontent.com/assets/15381269/11762487/d2e8847e-a0f0-11e5-89ac-8ee1f3281d59.jpg)

**Comment by stockfishdeveloper** [comment]
Ok Dmitry, the problem has to do with the computer you are using. If you have another computer, try running the compiled program on there. Let me know if it works. It is strange that the program I released on Github is working for you, but the version that you built is not working...

Dave

**Comment by stockfishdeveloper** [comment]
Could you perhaps post a video of you executing the program and doing whatever else you are doing in Dev-cpp?
Thank you
Dave

**Comment by DmitryAleksandrovich** [comment]
I need to install software for video recording.
I will try to understand himself.
Thank you.

**Comment by stockfishdeveloper** [comment]
Ok, I am going somewhere for about an hour; I will respond after that.
Thanks,
Dave

**Comment by stockfishdeveloper** [comment]
Hi Dmitry,
Try CamStudio for videoing: camstudio.org/

Dave

**Comment by DmitryAleksandrovich** [comment]
Thank you, Dave.
I will record video what I am doing in Dev-Cpp.

**Comment by stockfishdeveloper** [comment]
If you are having trouble posting the video here, maybe you could put it on mediafire(https://www.mediafire.com/) or something so I can download it.
Dave

**Comment by DmitryAleksandrovich** [comment]
Thank you.
I'll think of something and I'll post video.
Just, today I was very busy.

Thanks.

**Comment by stockfishdeveloper** [comment]
Ok, there's no rush.

Dave

**Comment by stockfishdeveloper** [comment]
Are you able to video in Dev-cpp?
Dave

**Comment by DmitryAleksandrovich** [comment]
Hello David!
I go through stages of selection in IT-company.
I will be busy until Thursday. But after Thursday I will be back to the
project.

Thank you, Dima.

**Comment by stockfishdeveloper** [comment]
How is your IT work going?

**Comment by DmitryAleksandrovich** [comment]
Hi. I don't know yet. The results were not announced yet. The company (proramers) is resting now.
Meanwhile, I post the completed projects on GitHub.
How is your engine? How much more you work on it?

**Comment by stockfishdeveloper** [comment]
I have made a lot of progress on it; The engine is much faster and there is much more functionality in it. Good luck  on the job!

Dave

**Comment by DmitryAleksandrovich** [comment]
Thank you Dave!
Good luck in the development of engine!
